// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEvlcQKz81HjwmeOrqIT-dvsdh0Gt4wPE',
    appId: '1:175368234640:web:fb6d1416504468e8d99a15',
    messagingSenderId: '175368234640',
    projectId: 'social-network-together',
    authDomain: 'social-network-together.firebaseapp.com',
    storageBucket: 'social-network-together.firebasestorage.app',
    measurementId: 'G-GCD1GK6QRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywvOuGMsZ0v6FdYx5isf-Id1E90FlBc0',
    appId: '1:175368234640:android:a06f737901894275d99a15',
    messagingSenderId: '175368234640',
    projectId: 'social-network-together',
    storageBucket: 'social-network-together.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk-0aSgQuYkUSLnkpe39HKRXlbXqT7s6U',
    appId: '1:175368234640:ios:510df1d5ee26bf04d99a15',
    messagingSenderId: '175368234640',
    projectId: 'social-network-together',
    storageBucket: 'social-network-together.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk-0aSgQuYkUSLnkpe39HKRXlbXqT7s6U',
    appId: '1:175368234640:ios:510df1d5ee26bf04d99a15',
    messagingSenderId: '175368234640',
    projectId: 'social-network-together',
    storageBucket: 'social-network-together.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEvlcQKz81HjwmeOrqIT-dvsdh0Gt4wPE',
    appId: '1:175368234640:web:7964e817dcd7fc0cd99a15',
    messagingSenderId: '175368234640',
    projectId: 'social-network-together',
    authDomain: 'social-network-together.firebaseapp.com',
    storageBucket: 'social-network-together.firebasestorage.app',
    measurementId: 'G-9T9L68G894',
  );
}
